@echo off
echo Stopping any running dev servers...
taskkill /F /IM node.exe 2>nul
timeout /t 2 /nobreak >nul
echo Clearing cache...
rmdir /s /q node_modules\.cache 2>nul
echo Starting dev server...
npm start

